### ISSUE TITLE
Support for multiple users & decryption keys

### ISSUE THREAD

**Issue by wyatttroutman** [aws-samples/pgp-decryption-for-transfer-family#2]
Hello! Great work on this project--it solves a fairly common business requirement. It seems for form a strong basis for supporting multiple users, but is limited by only allowing a single decryption key. Since the user information is already stored in secrets manager, why not merge the decryption key into that secret and allow for multiple keys? 

Most use cases would, I think, expect to have a different key per "user."

Cheers.

**Comment by lawtonpittenger** [comment]
Hello! Now that PGP decryption is a built-in Transfer Family Managed Workflow step, this can be accomplished! Please refer to this [blog post](https://aws.amazon.com/blogs/storage/encrypt-and-decrypt-files-with-pgp-and-aws-transfer-family/) for more information on how to set it up. :)
