### ISSUE TITLE
Lambda layer doesnot work

### ISSUE THREAD

**Issue by surajtikoo** [aws-samples/pgp-decryption-for-transfer-family#4]
After using this lambda layer is not able to find the module named 'gnupg' Traceback

**Comment by lawtonpittenger** [comment]
Did you run this [script](https://github.com/aws-samples/pgp-decryption-for-transfer-family/blob/main/setupEnvironment.sh) in Cloudshell? If yes, did you receive any errors? The intended output of the script will be the ARN for the newly created Lambda layer.
